language: node_js

node_js:
    - '0.10'

before_install:
    - npm install -g grunt-cli
    - npm install -g bower
    - gem install sass --version "=3.2.12"

install:
    - npm install
    - bower install

before_script:
    - grunt build
